import faker from 'faker/locale/en_IND';
export const postLists=[{
    id:faker.random.uuid(),
    name:faker.name.findName(),
    avatar:faker.image.avatar(),
    image:faker.image.image(),
    title:faker.lorem.slug(),
    sentences:faker.lorem.sentences(),
    starred:false,
    likes:Math.floor(Math.random() * 100) + 1,
    comment:[{name:faker.name.firstName(),
            comment:faker.lorem.sentence(),
            avatar:faker.image.avatar(),
            like:''},{name:faker.name.firstName(),
                comment:faker.lorem.sentence(),
                avatar:faker.image.avatar(),
                like:''}],
    bookmark:''
},{id:faker.random.uuid(),
    name:faker.name.findName(),
    avatar:faker.image.avatar(),
    image:faker.image.image(),
    title:faker.lorem.slug(),
    sentences:faker.lorem.sentences(),
    starred:false,
    likes:Math.floor(Math.random() * 100) + 1,
    comment:[{name:faker.name.firstName(),
            comment:faker.lorem.sentence(),
            avatar:faker.image.avatar(),
            like:''}],
    bookmark:''
},{id:faker.random.uuid(),
    name:faker.name.findName(),
    avatar:faker.image.avatar(),
    image:faker.image.image(),
    title:faker.lorem.slug(),
    sentences:faker.lorem.sentences(),
    starred:false,
    likes:Math.floor(Math.random() * 100) + 1,
    comment:[{name:faker.name.firstName(),
            comment:faker.lorem.sentence(),
            avatar:faker.image.avatar(),
            like:''}],
    bookmark:''
},{id:faker.random.uuid(),
    name:faker.name.findName(),
    avatar:faker.image.avatar(),
    image:faker.image.image(),
    title:faker.lorem.slug(),
    sentences:faker.lorem.sentences(),
    starred:false,
    likes:Math.floor(Math.random() * 100) + 1,
    comment:[{name:faker.name.firstName(),
            comment:faker.lorem.sentence(),
            avatar:faker.image.avatar(),
            like:''}],
    bookmark:''
}

]